config/routes.rb
ThreadedSalesApp::Application.routes.draw do

  devise_for :users
  
  resources :users, only: [:show, :index]
  resources :posts, only: [:index, :show, :create]
  resources :jobs, only: [:index, :new, :create]

  get 'events'  => 'static_pages#events'


  get '/posts/new/(:parent_id)', to: 'posts#new', as: :new_post


  root     'posts#index'

 
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	acts_as_tree order: 'created_at DESC', dependent: :delete_all
	
end

app/models/user.rb
class User < ActiveRecord::Base
 has_many :posts, dependent: :destroy
 has_many :jobs, dependent: :destroy
 mount_uploader :avatar, AvatarUploader

 devise :database_authenticatable, :registerable,
 :recoverable, :rememberable, :trackable, :validatable

 protected
def confirmation_required?
  false
end
 
end
# Include default devise modules. Others available are:
# :lockable, :timeoutable and :omniauthable,  :confirmable

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:email, :name, :lastname, :company, :title, :password, :password_confirmation, :avatar, :avatar_cache]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

	
	def index
		@jobs = Job.all.order("created_at DESC")
	end


	def new
		@job = current_user.jobs.build
	end

	def create
		@job = current_user.jobs.build(job_params)
		if @job.save
			redirect_to jobs_path
		else
			render 'new'
		end
	end

	private

	def job_params
		params.require(:job).permit(:company, :position, :city, :contact)
	end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	require 'rails_autolink'
	before_action :authenticate_user!, except: [:index]

	def index
		@post = Post.new
		@posts = Post.hash_tree
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = current_user.posts.build(parent_id: params[:parent_id])
	end

	def create
		if params[:post][:parent_id].to_i > 0
    		parent = Post.find_by_id(params[:post].delete(:parent_id))
    		@post = parent.children.build(post_params)
    		

    	else
    		@post = current_user.posts.build(post_params)
    	end

		if @post.save
			flash[:success] = 'Your post was successfully added!'
			redirect_to posts_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
	end

	def destroy
		
	end

	private

	

	def post_params
		params.require(:post).permit(:content).merge(user_id: current_user.id)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def events
	end

	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def new
	end

	def index
		@users = User.paginate(page: params[:page])
	end

	def show
		@user = User.find(params[:id])
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def posts_tree_for(posts)
    posts.map do |post, nested_posts|
      render(post) +
          (nested_posts.size > 0 ? content_tag(:div, posts_tree_for(nested_posts), class: "replies") : nil)
    end.join.html_safe
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.erb
<p>
	
<%= form_for @job do |f| %>

	<div class="form-group">    
		<%= f.text_field :company, class: 'form-control', placeholder: "Company" %> 
	</div>

	<div class="form-group">    
		<%= f.text_field :position, class: 'form-control', placeholder: "Position" %> 
	</div>

	<div class="form-group">    
		<%= f.text_field :city, class: 'form-control', placeholder: "City" %> 
	</div>

	<div class="form-group">    
		<%= f.text_field :contact, class: 'form-control', placeholder: "Contact info" %> 
	</div>


	<div class="post_button">
		<%= f.submit "Post", class: "btn btn-info" %>
	</div>

<% end %>
	
</p>

app/views/jobs/index.html.erb
<div class="container job_list">

<h1>New Sales Job Opportunities</h1></br>

<%= link_to "Post a new oppty", new_job_path, class: "btn btn-info" %>

<% @jobs.each do |job| %>

<div class="panel panel-info">
  <!-- Default panel contents -->
  <div class="panel-heading">New Opportunity!</div>
  

  <!-- List group -->
  <ul class="list-group">
    <li class="list-group-item">Created: <%= time_ago_in_words(job.created_at) %> ago </li>
    <li class="list-group-item">Posted by: <%= job.user.name.capitalize %> <%= job.user.lastname.capitalize %> </li>
    <li class="list-group-item">Company: <%= job.company %>  </li>
    <li class="list-group-item">Position: <%= job.position %>  </li>
    <li class="list-group-item">City: <%= job.city %>  </li>
    <li class="list-group-item">Contact for more info: <%= job.contact %> </li>
  
  </ul>
</div>

<% end %>

</div>

app/views/jobs/new.html.erb
<h1 class="job_list">Post a new job opportunity!</h1></br>
 
 
<%= render 'form' %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "glengarry highlands", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        
          <li><%= link_to "Events", events_path, id: "menu" %></li>
          <li><%= link_to "Members", users_path, id: "menu" %></li>
          <li><%= link_to "Who's Hiring?", jobs_path, id: "menu" %></li>
          
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <div class="account"><%= current_user.name.capitalize %><b class="caret"></b></div>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile",current_user, id: "drop" %></li>
              <li><%= link_to "Settings", edit_user_registration_path, id: "drop" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete", id: "drop" %>
              </li>
            </ul>
          </li>
      </ul>
    </nav>
  </div>
</header>

<% else %>
         
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThreadedSalesApp</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <% if user_signed_in? %>

      <body>

            <%= render 'layouts/header' %>
             
            <div class="container">
              <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %>">
                  <button type="button" class="close" data-dismiss="alert">&times;</button>
                  <%= value %>
                </div>
              <% end %>
            </div>
             
            <div class="container">
              <%= yield %>
            </div>
       
      </body>

  <% else %>

    <div class="container">
              <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %>">
                  <button type="button" class="close" data-dismiss="alert">&times;</button>
                  <%= value %>
                </div>
              <% end %>
            </div>

      <body class="home">
         
        <div class="container">
          <%= yield %>
        </div>
       
      </body>

  <% end %>

</html>

app/views/posts/_form.html.erb
<p>
	
<%= form_for @post do |f| %>

	<%= f.hidden_field :parent_id %>

	<div class="form-group">    
		<%= f.text_field :content, class: 'form-control', placeholder: "Share something here..." %> 
	</div>
	
	<div class="post_button">
		<%= f.submit "Post", class: "btn btn-info" %>
	</div>

<% end %>
	
</p>

app/views/posts/_post.html.erb
<div class="media">
    <div class="media-left">
        <div class="style_image">
          <% if post.user.avatar.url.present? %>
              <%= image_tag(post.user.avatar.url,:style => 'border-radius: 15%;') %>
          <% else %>  
          <a href="#">
            <img class="media-object" src="http://placehold.it/50x50" alt="...">
          </a>
          <% end %>
        </div>  
    </div>
  <div class="media-body">

        <%= auto_link(post.content) %></br>

    <div class="details">

      	<%= link_to time_ago_in_words(post.created_at), post_path(post), id: "time_ago" %> ago by <%=link_to post.user.name.capitalize, post.user, id: "time_ago" %> | <% from_reply_form ||= nil %>

        <% unless from_reply_form %>

          <%= link_to 'reply', new_post_path(post.id), id: "time_ago" %> | <%= link_to "delete", '#', id: "time_ago" %>

        <% end %>

    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% if user_signed_in? %>

<div class="col-md-3">
</div>

<div class="col-md-6">

	<div class="row">
		<%= render 'form' %></br>
	</div>

	<div class="row">
	 	<%= posts_tree_for @posts %>

	</div>
</div>

<div class="calendar col-md-3">
   <div class="panel panel-info">
  <!-- Default panel contents -->
  <div class="panel-heading">Next Glengarry Event!</div>
  
  <!-- List group -->
  <ul class="list-group">
    <li class="list-group-item"><%= link_to "8/8/15 Scramble Golf Tourney", events_path %></li>
  </ul>
</div>


</div>

<% else %>
        
        <div class="jumbotron">
            <div class="home-content">
                <div class="home-content-inner">
                    <h1>Welcome to the club.</h1>
                    
                    <p>Glengarry Highlands is a community for top salespeople.</p>
                    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-info" %>
                    <%= link_to "Log in", new_user_session_path, class: "btn btn-info" %>
                </div>
            </div>
       </div>

<% end %>

app/views/posts/new.html.erb
<h1>Reply to this post!</h1>
 
<% if @post.parent %>
  <%= render 'post', post: @post.parent, from_reply_form: true %>
<% end %>
 
<%= render 'form' %>

app/views/posts/show.html.erb
<h2>Message</h2>
<P>

	<%= render @post %>

</P>

app/views/static_pages/events.html.erb
<div class="panel panel-info">
  <!-- Default panel contents -->
  <div class="panel-heading">Upcoming Glengarry Events!</div>
  

  <!-- List group -->
  <ul class="list-group">
    <li class="list-group-item">Saturday, August 8th - Scramble Golf Tournament at Callipe Preserve in Pleasanton</li>
    <li class="list-group-item">Tuesday, August 15th, 7:00pm - Dinner at Bobo's on Lombard Street in SF </li>
  
  </ul>
</div>

<p>*E-Mail Ryan [ryan.mindigo@gmail.com] if you are interested in attending any of these events.</p>

app/views/static_pages/index.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Upcoming Glengarry Events!</div>
  

  <!-- List group -->
  <ul class="list-group">
    <li class="list-group-item">Saturday, August 8th - Scramble Golf Tournament at Callipe Preserve in Pleasanton</li>
    <li class="list-group-item">Tuesday, August 15th, 7:00pm - Dinner at Bobo's on Lombard Street in SF </li>
  
  </ul>
</div>

<p>*E-Mail Ryan [ryan.mindigo@gmail.com] if you are interested in attending any of these events.</p>

app/views/users/_user.html.erb
<div class="media">
  <div class="media-left">
    <% if user.avatar.url.present? %>
        <%= image_tag(user.avatar.url) %>
    <% else %>  
    <a href="#">
      <img class="media-object" src="http://placehold.it/50x50" alt="...">
    </a>
    <% end %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= link_to user.name.capitalize, user %> <%= user.lastname.capitalize %></h4>
    	<li> Joined <%= user.created_at.strftime("%m-%d-%y") %></li>
    	<li>Works for <%= user.company %> as <%= user.title %></li>
      <li><%= user.email %></li>
  </div>
</div>

app/views/users/index.html.erb
<h1 class="job_list">Members</h1></br>

<%= will_paginate %>

<ul class="users"> 
      <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
  <div class="col-md-3">

  	<h1>Profile Page</h1>

  	 <section class="users">
      <h5>
       
       <%= render @user  %>
      </h5>
    </section>

  </div>

  <div class="col-md-6">
   	<section class="show_posts">

		<%= render @user.posts %>

	</section>
  </div>
  